config/routes.rb
Rails.application.routes.draw do
 

  get 'sessions/new'

  root 'static_pages#home'
  #get '/static_pages/',       to:'static_pages#home'
  #get  '/home',    to:'static_pages#home'
  get    '/help',    to:'static_pages#help', as:'help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'   
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
	before_save { self.email = email.downcase }
	mount_uploader :cover,AvatarUploader
	validates :name, presence: true, length: { maximum: 50 } 
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
	validates :email, presence: true, length: { maximum: 255 },
                 	  format: { with: VALID_EMAIL_REGEX },
                  	uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #返回指定字符串的哈希摘要
  def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
 		  BCrypt::Password.create(string,cost: cost)
 	end

  #返回一个随机令牌
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  #在持久会话中记住用户
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest,User.digest(remember_token))
  end

  #如果指定的令牌和摘要匹配，返回true
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #忘记用户
  def forget
    update_attribute(:remember_digest,nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		#登入用户，然后重定向到用户的资料页面
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_to user
  	else
  		#创建一个错误消息
  		flash.now[:danger] = '无效的邮箱或密码'
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def about
  end
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	   if @user.save
            log_in @user
            #format.html { redirect_to @user, notice: '欢迎来到德莱联盟！' }
            #format.json { render :show, status: :created, location: @user }
            flash[:success] = "欢迎来到德莱联盟！"
            redirect_to @user
  	   else
  	        render 'new'
  	   end
  end

  def edit
    @user = User.find_by(params[:id])
  end

  def update
    @user = User.find_by(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = @user.id
      redirect_to @user 
    else
      render 'edit' 
    end
  end


  private

  def user_params
  	params.require(:user).permit(:name, :email, :password,
  									             :password_confirmation,:cover)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# 根据所在的页面返回完整的标题 
	def full_title(page_title = '')
		base_title = "Ruby on Rails Tutorial Sample App" 
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title end
		end
	end

app/helpers/sessions_helper.rb
module SessionsHelper
	#登入指定的用户
	def log_in(user)
		session[:user_id] = user.id
	end

	# 返回cookie中记忆令牌对应的用户
	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	#如果用户已登录，返回true，否则返回flase
	def logged_in?
		!current_user.nil?
	end

	#在持久会话中记住用户
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	#忘记持久会话
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	#退出当前用户
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# 返回指定用户的 Gravatar 
	def gravatar_for(user,options = {size: 40 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = user.cover
        image_tag(gravatar_url, alt: user.name, class: "gravatar",size:10*10)
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer"> 
	<small>
		The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
	</small>
	<nav> 
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul> 
	</nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
    	<div class="cotainer">
    		<%= link_to "sample app",root_path,id:"logo"  %>
    		<nav>
    			<ul class="nav navbar-nav navbar-right">
    				<li><%= link_to "Home",root_path  %></li>
    				<li><%= link_to "Help",help_path %></li>
                    <% if logged_in? %>
                        <li><%= link_to "Users","#" %></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">用户<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "我的空间",current_user %></li>
                            <li><%= link_to "设置",edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li><%= link_to "退出",logout_path,method: :delete %>
                            </li>
                        </ul>
                    </li>
                    <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                    <% end%>

                </ul>
    				
    		</nav>
    	</div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type,message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    	<%= yield%>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count,"error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="http://www.railstutorial.org/">About | Ruby on Rails Tutorial Sample App</a> sample application.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %> 
<h1>Contact</h1>
<p>
	Contact the Ruby on Rails Tutorial about the sample app at the
<a href="http://www.railstutorial.org/contact">contact page</a>. 
</p>

app/views/static_pages/help.html.erb
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="http://www.railstutorial.org/">
Help | Ruby on Rails Tutorial Sample App</a> sample application.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to the Sample App</h1>
	<h2>
		This is the home page for the
		<a href="http://www.baidu.com">百度一下</a>你就知道
	</h2>
	
		<%= link_to "Sign up now!",signup_path,class: "btn btn-lg btn-primary" %>
	
</div>
<%= link_to image_tag("rails.png",alt:"Rails logo",width:150,height:150),'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
    <%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages',object: @user %>
		
		<%= f.label :用户名 %>
		<%= f.text_field :name, class: 'form-control',value: "" %>
		<%= f.text_field :id, class: 'form-control',value: params[:id] %>
		<%= f.label :邮箱 %>
		<%= f.email_field :email, class: 'form-control',value: "" %>

		<%= f.label :密码 %>
		<%= f.password_field :password, class: 'form-control' %>

		<%= f.label :确认密码 %>
		<%= f.password_field :password_confirmation, class: 'form-control' %>

		<%= f.label :头像 %>
		<%= f.file_field :cover,class: 'form-control' %>

		<%= f.submit yield(:button_text), class: "btn btn-primary" %>
	<% end %> 

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text,"保存修改") %>
<h1>编辑用户信息</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text,'注册')%>
<h1>注册</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			
				<%= gravatar_for @user %>
			<h1>
				<%= @user.name %>
				
			</h1>
		</section>
	</aside>
</div>